apiVersion: v1
kind: Service
metadata:
  name: my-aes-portal
  namespace: default
spec:
  selector:
    app: aes-portal-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
