apiVersion: v1
kind: Service
metadata:
  name: my-redis
  namespace: redis
spec:
  selector:
    app: redis-deployment
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP